name: DCO
on:
  workflow_call:
    inputs:
      exclude-emails:
        type: string
        description: 'Comma-separated list of emails that should be ignored during DCO checks'
        required: false
        default: ''
  pull_request:
  push:
    branches:
      - "master"
jobs:
  dco-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DCO_CHECK_VERBOSE: '1'
          DCO_CHECK_EXCLUDE_EMAILS: ${{ inputs.exclude-emails }}
        run: |
          pip3 install -U dco-check
          dco-check
